### ISSUE TITLE
Not seeing focus rectangle for ReactJS app insider a WebView

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/TVHelpers#14]
Repro -

1) Create (JavaScript) Hosted Web App.
2) Point to a local HTML file that hosts a WebView.
3) Point WebView to a ReactJS site.
4) Add Directional Navigation JS to container and WebView sites
5) Note that focus rectangle does not appear when navigating with Controller on Xbox with D-Pad

**Comment by robcamer** [comment]
Please ensure that you run ReactJS within an iFrame, which you can set to 100% height / width.  Please look at the React JS sample (and readme) for more info.  Thanks!
