### ISSUE TITLE
no such interface supported

### ISSUE THREAD

**Issue by richcarr** [Microsoft/TVHelpers#17]
When disposing of MediaPlayer after an error in playback (the video src URL returned 404), an error "No such interface supported" is thrown in MediaPlayer.dispose() when trying to remove _errorFlyout from DOM. 

Narrowed it down to line ~21231:
    if (this._errorFlyout) {
        this._errorFlyout.removeEventListener("beforeshow", this._handleFlyoutOpenCallbackBind);
        this._errorFlyout.removeEventListener("afterhide", this._handleFlyoutCloseCallbackBind);
        _Global.document.body.removeChild(this._errorFlyout); // THIS LINE THROWS
        this._errorFlyout.dispose();
    }

Note that after the error occurs, I replace the mediaElement with another working video, let that play, then dispose.

**Comment by payzer** [comment]
I just checked in a fix for this issue,
