### ISSUE TITLE
Question: can I use the mediaPlayer as the UI

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#20]
Can I use the MediaPlayer as the UI for a different video player? I just want to use the MediaPlayer's buttons to communicate to my player's API. Is that possible?

**Comment by payzer** [comment]
Yes this should be possible. Check out this doc to see if it suits your needs:
https://github.com/Microsoft/TVHelpers/wiki/Create-a-Custom-MediaElementAdapter
