### ISSUE TITLE
Cursor not being hidden automatically

### ISSUE THREAD

**Issue by jwiese-ms** [Microsoft/TVHelpers#23]
The mouse pointer is not being hidden after X time when a video is played, it should be.

**Comment by daniel-dias** [comment]
I have this problem when starting the App.

I have a UWP with a webview.
And when the app starts, the Xbox cursor appears and i have to press "A" in the Xbox controller to make it disappear.

Is there a way to remove it completely but still use the directional navigation?

Thanks.

**Comment by payzer** [comment]
This documentation might help you: https://msdn.microsoft.com/en-us/windows/uwp/xbox-apps/how-to-disable-mouse-mode

**Comment by Spatacoli** [comment]
The issue is on Desktop Windows 10 the mouse pointer doesn't disappear after X seconds when a video is being played in full screen mode.
