### ISSUE TITLE
I'm not able to run the "csharp MediaAppSample" on build 14388

### ISSUE THREAD

**Issue by bdirgo** [Microsoft/TVHelpers#24]
I just downloaded this project as a zip from Github, and when I click on the .sln to open the project in Visual Studio 2015 it fails to load. It has the error,  
```
The mappings for the solution could not be found.
The mappings for the solution could not be found.
The mappings for the solution could not be found.
The active solution has been temporarily disconnected from source control because the server is unavailable.
``` 
 Windows SDK 14388 is the only build I can download from the Windows Insider website. And the readme says to use the 14366 build. I'm sorry if I am missing something obvious, could you please help me open your example?

Thank you

**Comment by robcamer** [comment]
Hi,
               I updated the project to use the 14388 SDK.  As new SDK’s release on the insiders site, it’s pretty straight forward to update.


1.      Right-click on each project and select “unload project” .

2.      Edit “project name”

3.      Change TargetPlatformVersion to the new SDK and Save

4.      Right-click and click Reload

5.      You will need update References for projects that reference Windows Extensions for the UWP

a.      Remove the references to the extensions

                                                    i.     Windows Desktop Extensions for the UWP

                                                   ii.     Windows Mobile Extensions for the UWP

b.      Re-add the references to the necessary extensions


Thanks,
-Rob
