### ISSUE TITLE
Changing appearance of focused MessageDialog button

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#25]
I am using the DirectionalNavigation to get my Xbox app to shift its focus to the correct button. I am also using the Windows.UI.Popups.MessageDialog control to display an error message.

If the MessageDialog has multiple buttons, then I can use the left/right buttons to shift focus. That works but the appearance of the focused button doesn't appear very dramatic so it's not easy to know which button is in focus.

How do I ensure the buttons look differently when they are in focused? It doesn't seem like the buttons are affected by any CSS files.

**Comment by payzer** [comment]
Unfortunately it's not possible to alter the appearance of the Windows.UI.Popups.MessageDialog buttons. The reason is it isn't rendered in HTML, it's drawn as an overlay by the system.
