### ISSUE TITLE
TVJS.DirectionalNavigation is undefined

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#26]
I have a multi paged app. The directional JavaScript is working, but then I navigate to a new page and then back to the previous page and when I try to navigate to a new button on that page, I get a runtime error that says that TVJS.DirectionalNavigation is undefined.

Does anyone know what may be happening?

**Comment by payzer** [comment]
It could have to do with the load order of scripts. That's when I've seen that error. It's when TVJS is loaded after a script that references it.

**Comment by jackhand** [comment]
I think you're right. 

The 2nd page I was navigating to was a video player page. I had linked to another TVHelper JavaScript file "mediaplayer-1.0.0.0.js". I actually didn't end up using the mediaplayer so I just removed it. When I did, the runtime error stopped happening. 

The mediaplayer script must be overwriting the TVJS object.
