### ISSUE TITLE
On XboxOne, the enter button seems to be extra senstive

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#28]
When I test the app on the desktop, the directional navigation is just fine. However, on the XboxOne, the app seems to react to both onKeyDown and onKeyUp. So when the user presses the "A" button to select the video play/pause toggle button, the video momentarily pauses upon key down, but resumes upon key up. 

Has anyone else experienced this?

**Comment by payzer** [comment]
Sorry for the delayed reply. I tried out the same setup and am not seeing this behavior (playpause is only getting toggled on keyup). Perhaps it's another file that's also sending key events?

**Comment by jackhand** [comment]
I modified the code so that the _handleKeyUpEvent() event handler exists without executing any of its code. I added a "return;" to the 1st line of code of that method.

The Xbox app now works as expected

Obviously this is not a

**Comment by payzer** [comment]
Yes, that sounds less than ideal.

**Comment by jackhand** [comment]
p.s. If I remove the reference to the Directional Navigation JavaScript file, then the navigational control doesn't work on my opening page.

p.s.s. If I continue to have the reference to the Directional Navigation JavaScript file but comment out what happens when I select one of the hub headers AND replace the old code with a console.log() reference, then I can observe that the hub header handler reacts to BOTH key down and key up.

**Comment by jackhand** [comment]
So it looks like the problem is indeed originating from the DirectionalNavigation. I have modified the _handleKeyUpEvent() event handler so that the code immediately exits if it the app is running on an xbox. 

That fixes my issue. Not ideal, but sufficient until a fix has been found. Hopefully you can recreate this issue on your end so you can fix the issue

Contact me if you need further info.

**Comment by payzer** [comment]
If you have a repro, you could send I would like to take a look. I haven't been able to repro with our samples yet.
