### ISSUE TITLE
xbox one controller not working

### ISSUE THREAD

**Issue by colouredFunk** [Microsoft/TVHelpers#29]
The xbox controller isn't responding to any navigation... I'm using the examples but nothing seems to be working?

**Comment by payzer** [comment]
I just tried the sample and verified it's working. I also had someone else try to get another data point. Here are some things you can try:
1. Try running the basic sample in a browser and see if the arrow keys work for navigation.
2. Try running the sample on an Xbox and making sure you can use the controller to navigate the system UI - it's possible the controller isn't able to send input to the system.

**Comment by robcamer** [comment]
I added a Windows 10 JavaScript sample, TVHelpers/WinRTjs/BasicPlaybackApp, that demonstrates how to pull in tv.js into a Windows app.

There is also another sample named TVHelpers/WinRTjs/WebAppBasic that demonstrates how to pull-in a thirdparty script library, ReactJS.  Note that you would need to download and include the latest version of ReactJS manually for this sample to work.

Thanks,
-Rob
