### ISSUE TITLE
Browser hang with DirectionalNavigation and WinJS Menu

### ISSUE THREAD

**Issue by staxmanade** [Microsoft/TVHelpers#30]
Hey Team,

I'm trying to track down a strange issue that keeps hanging my browser(s). (Chrome & Edge).

I have a react-winjs app up and running and when I use a `<Menu` option I'm setting the `focusRoot` to the menu dom element when the menu is shown, and then `.focus()` some `<MenuItem` within the menu. 

Everything works great while I use the keyboard to navigate up and down within the menu, However the moment I'm either at the first menu item and try to go up, or the last menu item and press down, it sends the browser into something that feels like an infinite loop, the U.I. thread locks up and I can't get it back without killing the tab.

Have you ever run into something like this? I'm struggling to track down what's causing this or how to work around it.

I littered the `DirectionalNavigation` with console logs and here's an example of what I see:

1. I press a button that activates and selects the middle of 3 items in the menu. 
2. I press the `up` key to navigate to the first menu item and and notice the key down/up events within DirectionalNavigation get a `console.log`
3. It's now focused on the first item in the menu and I press up again.
4. I don't get either the key down or up logs on this action and it completely hangs the browser.

Have you ever seen something like this and have any thoughts on what it could be or how to debug it?

I am happy to setup a pairing session with someone to work through it if possible as this is currently blocking my keyboard (and soon to be testing controller) focus management work for an Win10/Xbox app I'm working on.

Thoughts?

**Comment by payzer** [comment]
Thank you for posting your question. Like you've guessed this sounds like an infinite loop. The best process for debugging these is:
1. Set a breakpoint in directionalnavigation-1.0.0.0.js in the following locations:
(line 578) _handleKeyDownEvent 
(line 604) _handleKeyUpEvent
(line 1001) _focusRoot = value;
(line 332) _findNextFocusElementInternal

2. Run your repro
3. In the debugging, you'll hit one of these breakpoints multiple times (for a normal focus move any one of wouldn't be called more than once so it let's say you see _findNextFocusElementInternal called 3 times, then that would be an issue).
4. For the breakpoint that keeps getting hit, look at the call stack to see what is triggering it. The thing at the top of the call stack will either be the culprit or give a good indicator to what the culprit it.

Let us know if you are able to solve the issue. If not, post back here & we can figure out a way to get you further help.

**Comment by staxmanade** [comment]
@payzer thanks for the feedback. This has been challenging to debug, primarily because the WinJS Menu object really likes to hide itself whenever focus is lost (which always happens when trying to access the debugger). However, I started littering any `keydown` functions in `WinJS` and have traced it down to...
`Menu._handleKeyDown` and have hacked together a work-around locally.

Basically, react-winjs is inserting an extra div into the dom that WinJS is not expecting when it's trying to handle focus navigation within the `Menu`

The following code-change fixed it for the (top of menu - navigate up option.

```diff
            // Set focus to previous focusable element in the menu (loop if necessary).
            //   Note: The loop works by first setting focus to the menu itself.  If the menu is
            //         what had focus before, then we break.  Otherwise we try the last child next.
            // Focus remains on the menu if nothing is focusable.
            Menu._focusOnPreviousElement = function (menu) {
                var _currentElement = _Global.document.activeElement;
                do {
                    if (_currentElement === menu) {
+                        // the react-winjs framework is adding an extra div so .lastElementChild won't
+                        // work here and causes an infinite loop - use querySelector to find last win-command
+                        _currentElement = _currentElement.querySelector('.win-command:last-child');
-                        _currentElement = _currentElement.lastElementChild;
                    } else {
                        _currentElement = _currentElement.previousElementSibling;
                    }

                    if (_currentElement) {
                        _currentElement.focus();
                    } else {
                        _currentElement = menu;
                    }

                } while (_currentElement !== _Global.document.activeElement);
            };
```

```diff
            // Set focus to next focusable element in the menu (loop if necessary).
            //   Note: The loop works by first setting focus to the menu itself.  If the menu is
            //         what had focus before, then we break.  Otherwise we try the first child next.
            // Focus remains on the menu if nothing is focusable.
            Menu._focusOnNextElement = function (menu) {
                var _currentElement = _Global.document.activeElement;

                do {
                    if (_currentElement === menu) {
+                        // the react-winjs framework is adding an extra div so .lastElementChild won't
+                        // work here and causes an infinite loop - use querySelector to find last win-command
+                        _currentElement = _currentElement.querySelector('.win-command:first-child');
-                        _currentElement = _currentElement.firstElementChild;
                    } else {
                        _currentElement = _currentElement.nextElementSibling;
                    }

                    if (_currentElement) {
                        _currentElement.focus();
                    } else {
                        _currentElement = menu;
                    }

                } while (_currentElement !== _Global.document.activeElement);
            };
```

If this is something you guys can incorporate into WinJS and publish that'd be great - but I feel since WinJS is sun-setting, I'll need to figure out how to build my own copy...

**Comment by payzer** [comment]
Thank for letting us know. I will pass on the feedback to the WinJS team, but like you mentioned about sun-setting, you'll want to build your own copy.
