### ISSUE TITLE
TVJS mediaplayer and the directional navigation JS doesnt work simultaneously.

### ISSUE THREAD

**Issue by codeclaysolken** [Microsoft/TVHelpers#32]
I am new to the xbox development and an beginner at javascript. I am trying to build a UWP in which I want to implement the media player to my app to use the xbox keypad controls with the video playback. Also, I am using the directional navigation functions like **focusableSelectors** like this:
                       
`TVJS.DirectionalNavigation.focusableSelectors.push('.some_div');.` 

But, when I use both the library, in order:

```
<link rel="stylesheet" href="./lib/tvjs/MediaPlayer/mediaplayer-1.0.0.0.css">
<script src="./lib/tvjs/DirectionalNavigation/directionalnavigation-1.0.0.0.js"></script>
<script src="./lib/tvjs/MediaPlayer/mediaplayer-1.0.0.0.js"></script>
```

 In debug it shows error 
`JavaScript runtime error: Unable to get property 'focusableSelectors' of undefined or null reference` 

Hence I am not able to use directionalnavigation specific functions.

**Please help.**

**Comment by payzer** [comment]
Thank you for posting the issue. We are looking into it.

**Comment by payzer** [comment]
In the meantime, as a workaround, it looks like if you flip the order of includes (include MediaPlayer 1st) then it doesn't throw the exception.

**Comment by payzer** [comment]
The fix is checked in. Thank you for reporting the issue.
