### ISSUE TITLE
Xbox Cursor not being hidden after application starts

### ISSUE THREAD

**Issue by daniel-dias** [Microsoft/TVHelpers#34]
I have previously posted this in another thread but it was a little misplaced, so i'm creating a new one.

This problem is when starting the App.

I have a UWP with a webview. When the app starts, the Xbox cursor appears and i have to press "A" in the Xbox controller to make it disappear.
If i press the "Xbox" button i go to the Xbox apps... but when i resume the app, the cursor appears again.

I have tried one suggestion that is using this: navigator.gamepadInputEmulation = "gamepad";

But with that the cursor still appears, and besides that, with this option none of the Key Events work.

Is there a way to remove it completely but still use the directional navigation, with the key events?

Thanks.

**Comment by payzer** [comment]
Thank you for your question. Have you tried navigator.gamepadInputEmulation = "keyboard";

That's what I use in my apps to hide the cursor & use directional navigation.

**Comment by daniel-dias** [comment]
Hi,

Thanks for your answer.
Yes, i have also tried that, but it doesn't seem to change anything, because the behaviour is the same: the cursor appears on the screen and when i press a button: A, B, X or Yor the Right Joystick it immediatly disappears.

**Comment by payzer** [comment]
That sounds like it might be a bug. The cursor is supposed to never appear if you set this property: navigator.gamepadInputEmulation = "keyboard";

Sometimes I've seen the cursor appear if some other piece of code is setting the navigator.gamepadInputEmulation property. Or if by chance there is XAML in your app, then XAML has another property for setting the cursor mode.

**Comment by payzer** [comment]
This one's been open for a while so I'm hoping you found a solution. If not, let us know :)
