### ISSUE TITLE
only timeline shows when pressing button (xbox)

### ISSUE THREAD

**Issue by vgrafe** [Microsoft/TVHelpers#37]
Hi,

When following the basic example for MediaPlayer and testing on xbox (hosted webapp), pressing the A button will bring the timeline, but nothing else appears. I'd like to give full control for the user (play/pause etc), am I missing something? I can't find methods to display the controls with js.

Thanks!

**Comment by payzer** [comment]
The default button set should be showing up. I'll give it a try now.

**Comment by payzer** [comment]
While I'm trying it out - one thing to check is whether the font file is being included. The buttons use font glyphs as icons so that could be it.

**Comment by vgrafe** [comment]
Right - checking now

**Comment by vgrafe** [comment]
My mistake! my dev server was deferring requests for the font file to another file. Thanks for pointing that out!
