### ISSUE TITLE
MediaPlayer/Edge possible memory leak when streaming HLS

### ISSUE THREAD

**Issue by vgrafe** [Microsoft/TVHelpers#38]
Hi, 

Some of my users experienced crashes on our xbox app. It looks like it is caused by the memory usage when streaming videos. I created a simple page, similar to the basic example, with a `.m3u8` of ours to see if it was caused by something else in our webapp. The memory usage reaches 2 gigs within minutes, then 4 gigs, then crashes.

Is there something I missed? I am not sure this is the right place to report this as it happens also when using a `<video>` element. 

Thanks for helping!

**Comment by vgrafe** [comment]
I forgot to attach a shot of visual studio profiler that illustrates how memory usages goes up without proper cleanup.
![screen shot 2017-04-05 at 11 11 55 am](https://cloud.githubusercontent.com/assets/3950855/24723243/c3d0b2e2-1a14-11e7-953a-122d4be4e24c.png)

**Comment by vgrafe** [comment]
Adding a gist to ease testing - [here it is](https://gist.github.com/vgrafe/d4abc450d94d3757e897de068c023b1d)

**Comment by payzer** [comment]
Thank you for reaching out, but posting this elsewhere will be better since it's more of a video pipeline issue. Posting on these forums would be the best place: https://social.msdn.microsoft.com/Forums

**Comment by vgrafe** [comment]
Thanks!
