### ISSUE TITLE
Question regarding DirectionalNav and initial focus.

### ISSUE THREAD

**Issue by joshuairl** [Microsoft/TVHelpers#39]
I'm having trouble setting initial focus.

I feel like I'm calling .focus() at the right time but it just won't take focus until I navigate using the keyboard or gamepad.  I really need it to set initial focus to the first video upon load but it just doesn't seem to work.

Am I missing something?

I noticed an issue relating to calling the "init()" manually, is this something I'll need to do maybe? instead of letting it default to DOMDocumentReady or whatever?

Thanks for any advice you can give!
Great work on this library!

**Comment by joshuairl** [comment]
Tried turning off automatic focus handling but still doesn't seem to respond to .focus(), not getting the focused box around it or anything.

`TVJS.DirectionalNavigation.enabled = false;`

**Comment by joshuairl** [comment]
So I'm guessing if I could somehow hold off the "init" and key bindings, maybe that would help?
Or am I missing something?

**Comment by payzer** [comment]
Thank you for the compliments on the library and thank you for your question.

The best way to set initial focus is to wait until everything loads. The most common issue with setting initial focus is that the DOM isn't fully rendered yet. So let's say your video is part of a page control. Usually the control will have an event to tell you it's done loading and then you can call .focus(). If you are developing for Edge only, then you can use setImmediate(function () { element.focus(); }) although your best bet is still to listen for any loading completed event on your page or control before setting focus.

Just to be safe, I usually will do a check like:

if (!document.activeElement) { video.focus();  }

This way if the user has moved before your focus code runs, then your code won't steal focus from wherever they navigated to.

**Comment by joshuairl** [comment]
Thanks for the response.
Sadly, it ended up being an issue of tabindex and it being a <div> :-/
