### ISSUE TITLE
After pressing Xbox button, cannot interact with app anymore

### ISSUE THREAD

**Issue by daniel-dias** [Microsoft/TVHelpers#41]
After pressing the Xbox button (when the sidebar of the xbox appears and let us open other apps), and then resuming the app, we cannot interact anymore with the app.

We see that the element has focus, but no more keypress events are fired anymore.
I've tried also to set a timeout that would set a certain element with focus, but the behaviour is the same.

After pressing that Xbox button, no button work anymore, and i have to Quit the app and Launch it again.

Is there anyway to resolve this?

Regards,
Daniel

**Comment by payzer** [comment]
Thank you for opening this issue. However, it sounds like it may be an operating system issue? The best place to file those are the MSDN forums: https://social.msdn.microsoft.com/Forums/en-US/home?searchTerm=UWP%20Xbox

**Comment by payzer** [comment]
I'll close the issue here since it sounds like an operating system issue. But if you think it might be an issue with the library, let us know and we can investigate.

**Comment by daniel-dias** [comment]
Hi,

I don't really know if its an issue with the OS or the library.
This is the first app that i develop for Xbox, does anyone that has made other apps for Xbox experienced this issue? Or is it just me?

**Comment by payzer** [comment]
I do a fair amount of app development and I haven't seen that issue before so I'm guessing it would be an OS issue.
