### ISSUE TITLE
XAML samples

### ISSUE THREAD

**Issue by davidezordan** [Microsoft/TVHelpers#6]
Hi,
are there any plans to include XAML samples for Xbox One UWP in addition to the WebView one?

Thanks,
Davide

**Comment by robcamer** [comment]
Hi David, Yes.  We are near completing an end-to-end responsive XAML sample that will include Xbox One.  It will ship this month.

Thanks,
-Rob

**Comment by davidezordan** [comment]
Thank you, Rob!
