### ISSUE TITLE
DirectionalNavigation doesn't provide Xbox Sounds

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#7]
The tvjs version of DirectionalNavigation doesn't provide the typical "Xbox" sound effects during certain events: i.e. when an item is highlighted, when an item is pressed/selected, when an operation is exited.

Will playing XBOX sounds be added to the logic of DirectionalNavigation?

**Comment by payzer** [comment]
Right now Xbox doesn't support playing system sounds in the current developer preview. When the ability to play system sounds is added to the operating system, the library will be updated to play sounds on focus movement.
