### ISSUE TITLE
DirectionalNavigation doesn't ensure focused item is visible

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#8]
When navigating through a ListView, I have found that the focused item is not always visible.

For example, I navigate to the right, the focused item changes and eventually falls out of view, until eventually a new focused item is selected and the listView automatically scrolls to display the focused item. However, there are a number of items in the listView that were not visible when they were in focus.

Is there a way to fix this? Is there a way to set the viewable area? Is this a bug?

**Comment by payzer** [comment]
This is a great suggestion for a sample. I will add it to our backlog and close this comment when the sample is posted.

**Comment by payzer** [comment]
We've added a sample that demonstrates scroll into view behavior:
https://github.com/Microsoft/TVHelpers/tree/master/tvjs/examples/DirectionalNavigation/ScrollIntoView

Note: the sample doesn't use the WinJS ListView (because we are trying to keep TVJS framework agnostic), but demonstrates the pattern one would use for any framework.

**Comment by jackhand** [comment]
thanks, @payzer 
I tried to listen for the focuschanging event but it is only triggered when it the focus leaves one hub section to another hub section. The event does not dispatch when the items within a hub section are gaining losing focus. Do I need to do something to fix that?

**Comment by payzer** [comment]
I looked at the sample again (https://github.com/Microsoft/TVHelpers/tree/master/tvjs/examples/DirectionalNavigation/ScrollIntoView) and I'm seeing focuschanging firing every time focus changes. Are you seeing something else?

**Comment by jackhand** [comment]
Yes, The reason is because the hub sections are not allowing the keyup/keydown events from bubbling up. It would seem that the winJS hub sections have been designed to listen to these events and display the items as highlighted.

So I have created a "onkeyboardnavigating" event listener on the hub section control and scroll the page if the item isn't into view. I am still doing this coding, so I have not perfected it just yet.

So any advice is welcomed. If you have any suggestion on a different way to accomplish this, then I am all ears.

**Comment by jackhand** [comment]
By the way, your sample does not include  what happens when the user uses the up/down arrows when the UI is in horizontal mode (i.e. the app is taking part of the screen.) I am also working on a fix for this too.

**Comment by payzer** [comment]
I see. Thank you for the context. 

You're correct, there was special work in an Xbox-only version of WinJS specifically for the hub control (we never released it broadly). In case it helps, here is that code - note it is based on a fork of WinJS 1.0 and has isn't the cleanest code in the world so apologies in advance :):

               _handleFocusChanging: function hub_handleFocusChanging(ev) {
                    var automaticFocus = XboxJS.UI.AutomaticFocus;
                    var key = WinJS.Utilities.Key;
                    if (automaticFocus) {
                        var keyCode = ev.detail.keyCode;
                        var nextFocusElement = ev.detail.nextFocusElement;
                        if (nextFocusElement) {

                            // Figure out if we are about to leave a hub section.
                            var nextFocusElementRect = nextFocusElement.getBoundingClientRect();
                            switch (keyCode) {
                                case key.leftArrow:
                                case key.gamepadDPadLeft:
                                case key.gamepadLeftThumbstickLeft:
                                    // Now figure out if we're skipping a section
                                    if (this._currentIndexForSezo > 0) {
                                        var nextSection = this.sections.getAt(this._currentIndexForSezo - 1).element;
                                        var nextSectionRect = nextSection.getBoundingClientRect();
                                        if (nextFocusElementRect.right < nextSectionRect.left) {

                                            // If we've skipped a section, we need to run the algorithm again, this time with the focusRoot
                                            // on the current hub section's element so that we'll either get nothing or an element within the
                                            // hub section.
                                            var previousFocusRoot = automaticFocus.focusRoot;
                                            automaticFocus.focusRoot = nextSection;
                                            var newNextFocusElement = automaticFocus.findNextFocusElement(keyCode);

                                            // If we still don't find anything (which means there's no interactive content in the curren hub section)
                                            // then we'll just focus on the nextFocusElement.
                                            if (newNextFocusElement) {
                                                newNextFocusElement.focus();
                                                // We replace nextFocusElement with the newNextFocusElement so the "scroll into view" code
                                                // below can act on the new element that should recieve focus.
                                                nextFocusElement = newNextFocusElement;
                                                nextFocusElementRect = newNextFocusElement.getBoundingClientRect();
                                                ev.preventDefault();

                                                // Choose one of the 4 focus sounds to play at random
                                                var indexOfFocusSoundToPlay = Math.ceil(Math.random() * 4);
                                                switch (indexOfFocusSoundToPlay) {
                                                    case 1:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                            XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                        }
                                                        break;
                                                    case 2:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus2) {
                                                            XboxJS.UI.Hub._sounds.elementFocus2.play();
                                                        }
                                                        break;
                                                    case 3:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus3) {
                                                            XboxJS.UI.Hub._sounds.elementFocus3.play();
                                                        }
                                                        break;
                                                    case 4:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus4) {
                                                            XboxJS.UI.Hub._sounds.elementFocus4.play();
                                                        }
                                                        break;
                                                    default:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                            XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                        }
                                                        break;
                                                }
                                            }

                                            // Restore the focusRoot
                                            automaticFocus.focusRoot = previousFocusRoot;
                                        }
                                    }
                                    var elapsedTimeSinceLastKeydownLeft = new Date().getTime() - this._lastKeydownLeft;
                                    this._lastKeydownLeft = new Date().getTime();
                                    // Figure out if we've hit a "threshold" & need to play an animation
                                    // Note: This behavior does not happen if the user if holding down the left direction
                                    if (nextFocusElementRect.left < this._leftBoundaryToTriggerFixedFocusMode) {
                                        // Call the animation API to bring it into view
                                        if (WinJS.UI.isAnimationEnabled() &&
                                            this._viewportElement.msZoomTo &&
                                            this._viewportElement.contains(nextFocusElement) &&
                                            !XboxJS.Utilities._isSnapped()) {
                                            var xScrollAmount = -1 * (this._leftBoundaryToTriggerFixedFocusMode - nextFocusElementRect.left);
                                            var xScrollPos = Math.max(0, this._viewportElement[this._names.scrollPos] + xScrollAmount);
                                            if (elapsedTimeSinceLastKeydownLeft > 250) {
                                                this._viewportElement.msZoomTo({ contentX: xScrollPos, contentY: 0, viewportX: 0, viewportY: 0 });
                                            } else {
                                                // If the user is holding down or pressing right in rapid succession then skip the animation.
                                                this._viewportElement[this._names.scrollPos] = xScrollPos;
                                            }
                                            // setActive() is cheaper than calling focus() which is what automatic focus will do
                                            WinJS.Utilities._trySetActive(nextFocusElement);
                                            ev.preventDefault();

                                            // Choose one of the 4 focus sounds to play at random
                                            var indexOfFocusSoundToPlay = Math.ceil(Math.random() * 4);
                                            switch (indexOfFocusSoundToPlay) {
                                                case 1:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                        XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                    }
                                                    break;
                                                case 2:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus2) {
                                                        XboxJS.UI.Hub._sounds.elementFocus2.play();
                                                    }
                                                    break;
                                                case 3:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus3) {
                                                        XboxJS.UI.Hub._sounds.elementFocus3.play();
                                                    }
                                                    break;
                                                case 4:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus4) {
                                                        XboxJS.UI.Hub._sounds.elementFocus4.play();
                                                    }
                                                    break;
                                                default:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                        XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                    }
                                                    break;
                                            }
                                        }
                                    }
                                    break;
                                case key.rightArrow:
                                case key.gamepadDPadRight:
                                case key.gamepadLeftThumbstickRight:
                                    // Now figure out if we're skipping a section
                                    if (this._currentIndexForSezo + 1 < this.sections.length) {
                                        var nextSectionRect = this.sections.getAt(this._currentIndexForSezo + 1).element.getBoundingClientRect();
                                        if (nextFocusElementRect.left > nextSectionRect.right) {

                                            // If we've skipped a section, we need to run the algorithm again, this time with the focusRoot
                                            // on the current hub section's element so that we'll either get nothing or an element within the
                                            // hub section.
                                            var previousFocusRoot = automaticFocus.focusRoot;
                                            automaticFocus.focusRoot = this.sections.getAt(this._currentIndexForSezo + 1).element;
                                            var newNextFocusElement = automaticFocus.findNextFocusElement(keyCode);

                                            // If we still don't find anything (which means there's no interactive content in the curren hub section)
                                            // then we'll just focus on the nextFocusElement.
                                            if (newNextFocusElement) {
                                                newNextFocusElement.focus();
                                                // We replace nextFocusElement with the newNextFocusElement so the "scroll into view" code
                                                // below can act on the new element that should recieve focus.
                                                nextFocusElement = newNextFocusElement;
                                                nextFocusElementRect = newNextFocusElement.getBoundingClientRect();
                                                ev.preventDefault();

                                                // Choose one of the 4 focus sounds to play at random
                                                var indexOfFocusSoundToPlay = Math.ceil(Math.random() * 4);
                                                switch (indexOfFocusSoundToPlay) {
                                                    case 1:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                            XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                        }
                                                        break;
                                                    case 2:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus2) {
                                                            XboxJS.UI.Hub._sounds.elementFocus2.play();
                                                        }
                                                        break;
                                                    case 3:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus3) {
                                                            XboxJS.UI.Hub._sounds.elementFocus3.play();
                                                        }
                                                        break;
                                                    case 4:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus4) {
                                                            XboxJS.UI.Hub._sounds.elementFocus4.play();
                                                        }
                                                        break;
                                                    default:
                                                        if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                            XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                        }
                                                        break;
                                                }
                                            }

                                            // Restore the focusRoot
                                            automaticFocus.focusRoot = previousFocusRoot;
                                        }
                                    }
                                    var elapsedTimeSinceLastKeydownRight = new Date().getTime() - this._lastKeydownRight;
                                    this._lastKeydownRight = new Date().getTime();
                                    // Figure out if we've hit a "threshold" & need to play an animation
                                    // Note: This behavior does not happen if the user if holding down the left direction
                                    if (nextFocusElementRect.right > this._rightBoundaryToTriggerFixedFocusMode) {
                                        // Call the animation API to bring it into view
                                        if (WinJS.UI.isAnimationEnabled() &&
                                            this._viewportElement.msZoomTo &&
                                            this._viewportElement.contains(nextFocusElement) &&
                                            !XboxJS.Utilities._isSnapped()) {
                                            var xScrollAmount = nextFocusElementRect.right - this._rightBoundaryToTriggerFixedFocusMode;
                                            var xScrollPos = Math.max(0, this._viewportElement[this._names.scrollPos] + xScrollAmount);
                                            if (elapsedTimeSinceLastKeydownRight > 250) {
                                                this._viewportElement.msZoomTo({ contentX: xScrollPos, contentY: 0, viewportX: 0, viewportY: 0 });
                                            } else {
                                                // If the user is holding down or pressing right in rapid succession then skip the animation.
                                                this._viewportElement[this._names.scrollPos] = xScrollPos;
                                            }

                                            // setActive() is cheaper than calling focus() which is what automatic focus will do
                                            WinJS.Utilities._trySetActive(nextFocusElement);
                                            ev.preventDefault();

                                            // Choose one of the 4 focus sounds to play at random
                                            var indexOfFocusSoundToPlay = Math.ceil(Math.random() * 4);
                                            switch (indexOfFocusSoundToPlay) {
                                                case 1:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                        XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                    }
                                                    break;
                                                case 2:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus2) {
                                                        XboxJS.UI.Hub._sounds.elementFocus2.play();
                                                    }
                                                    break;
                                                case 3:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus3) {
                                                        XboxJS.UI.Hub._sounds.elementFocus3.play();
                                                    }
                                                    break;
                                                case 4:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus4) {
                                                        XboxJS.UI.Hub._sounds.elementFocus4.play();
                                                    }
                                                    break;
                                                default:
                                                    if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                        XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                    }
                                                    break;
                                            }
                                        }
                                    }
                                    break;
                                case key.downArrow:
                                case key.gamepadDPadDown:
                                case key.gamepadLeftThumbstickDown:
                                    // We don't want to move to another section when moving down
                                    if (this._viewportElement.contains(document.activeElement)) {
                                        var currentSectionElement = this.sections.getAt(this._currentIndexForSezo).element;
                                        var currentSectionRect = currentSectionElement.getBoundingClientRect();
                                        if (nextFocusElementRect.right < currentSectionRect.left ||
                                            nextFocusElementRect.left > currentSectionRect.right) {
                                            // Note: We need code to check if the current focused item is in a flyout, because it's possible to embed a flyout
                                            // inside of a hub section. For instance, a ratingPicker. Developers shouldn't do this and once we fix the RatingPicker & 
                                            // other flyout-based controls to attach their flyouts to the body we can get rid of this code and always call preventDefault.
                                            var isFocusInFlyout = false;
                                            var overlays = currentSectionElement.querySelectorAll(".win-overlay");
                                            if (overlays.length) {
                                                for (var i = 0, len = overlays.length; i < len; i++) {
                                                    if (overlays[i].contains(nextFocusElement)) {
                                                        isFocusInFlyout = true;
                                                        break;
                                                    }
                                                }
                                            }
                                            if (!isFocusInFlyout) {
                                                ev.preventDefault();
                                            }
                                        } else {
                                            // Going down may also cause us to land on an element that is not entirely in the viewport. If it is not in the
                                            // viewport then we need to scroll it into view.
                                            if (nextFocusElementRect.left < this._leftBoundaryToTriggerFixedFocusMode) {
                                                // Call the animation API to bring it into view
                                                if (WinJS.UI.isAnimationEnabled() &&
                                                    this._viewportElement.msZoomTo &&
                                                    this._viewportElement.contains(nextFocusElement) &&
                                                    !XboxJS.Utilities._isSnapped()) {
                                                    var xScrollAmount = -1 * (this._leftBoundaryToTriggerFixedFocusMode - nextFocusElementRect.left);
                                                    var xScrollPos = Math.max(0, this._viewportElement[this._names.scrollPos] + xScrollAmount);
                                                    if (elapsedTimeSinceLastKeydownLeft > 250) {
                                                        this._viewportElement.msZoomTo({ contentX: xScrollPos, contentY: 0, viewportX: 0, viewportY: 0 });
                                                    } else {
                                                        // If the user is holding down or pressing right in rapid succession then skip the animation.
                                                        this._viewportElement[this._names.scrollPos] = xScrollPos;
                                                    }
                                                    // setActive() is cheaper than calling focus() which is what automatic focus will do
                                                    WinJS.Utilities._trySetActive(nextFocusElement);
                                                    ev.preventDefault();

                                                    // Choose one of the 4 focus sounds to play at random
                                                    var indexOfFocusSoundToPlay = Math.ceil(Math.random() * 4);
                                                    switch (indexOfFocusSoundToPlay) {
                                                        case 1:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                                XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                            }
                                                            break;
                                                        case 2:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus2) {
                                                                XboxJS.UI.Hub._sounds.elementFocus2.play();
                                                            }
                                                            break;
                                                        case 3:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus3) {
                                                                XboxJS.UI.Hub._sounds.elementFocus3.play();
                                                            }
                                                            break;
                                                        case 4:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus4) {
                                                                XboxJS.UI.Hub._sounds.elementFocus4.play();
                                                            }
                                                            break;
                                                        default:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                                XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                            }
                                                            break;
                                                    }
                                                }
                                            } else if (nextFocusElementRect.right > this._rightBoundaryToTriggerFixedFocusMode) {
                                                // Call the animation API to bring it into view
                                                if (WinJS.UI.isAnimationEnabled() &&
                                                    this._viewportElement.msZoomTo &&
                                                    this._viewportElement.contains(nextFocusElement) &&
                                                    !XboxJS.Utilities._isSnapped()) {
                                                    var xScrollAmount = nextFocusElementRect.right - this._rightBoundaryToTriggerFixedFocusMode;
                                                    var xScrollPos = Math.max(0, this._viewportElement[this._names.scrollPos] + xScrollAmount);
                                                    if (elapsedTimeSinceLastKeydownRight > 250) {
                                                        this._viewportElement.msZoomTo({ contentX: xScrollPos, contentY: 0, viewportX: 0, viewportY: 0 });
                                                    } else {
                                                        // If the user is holding down or pressing right in rapid succession then skip the animation.
                                                        this._viewportElement[this._names.scrollPos] = xScrollPos;
                                                    }

                                                    // setActive() is cheaper than calling focus() which is what automatic focus will do
                                                    WinJS.Utilities._trySetActive(nextFocusElement);
                                                    ev.preventDefault();

                                                    // Choose one of the 4 focus sounds to play at random
                                                    var indexOfFocusSoundToPlay = Math.ceil(Math.random() * 4);
                                                    switch (indexOfFocusSoundToPlay) {
                                                        case 1:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                                XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                            }
                                                            break;
                                                        case 2:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus2) {
                                                                XboxJS.UI.Hub._sounds.elementFocus2.play();
                                                            }
                                                            break;
                                                        case 3:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus3) {
                                                                XboxJS.UI.Hub._sounds.elementFocus3.play();
                                                            }
                                                            break;
                                                        case 4:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus4) {
                                                                XboxJS.UI.Hub._sounds.elementFocus4.play();
                                                            }
                                                            break;
                                                        default:
                                                            if (XboxJS.UI.Hub._sounds.elementFocus1) {
                                                                XboxJS.UI.Hub._sounds.elementFocus1.play();
                                                            }
                                                            break;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    break;
                                    // Note: There is no special logic for down. Also, at this time We do not support special focus handling for the 
                                    // hub control in vertical layout mode.
                                default:
                                    break;
                            }
                        }
                    }
                },

**Comment by jackhand** [comment]
I had wished XboxJS was going to make it for the Windows 10 release so it would have been easier to program for Xbox using JavaScript. Oh well!

Is there any way I can adjust and use this code?

**Comment by payzer** [comment]
Unfortunately there isn't a way for that code to "just work". 

Do you have a contact at Microsoft? If so, can you have them connect you with me via email. Unfortunately, Git doesn't have a way to exchange email addresses without giving it out to the internet otherwise I'd give you mine.
