### ISSUE TITLE
DirectionalNavigation doesn't listen for back events

### ISSUE THREAD

**Issue by jackhand** [Microsoft/TVHelpers#9]
Should the DirectionalNavigation listen for when the user uses the Back/ESC button to back out of a pop up window or navigate back a page?

**Comment by payzer** [comment]
That is a really great suggestion. Unfortunately, the hard part about having esc, back or Gamepad B navigate back automatically is that depending on the framework you are using back means different things. For instance, Angular uses a single page navigation model but modifies the URL. A traditional web site navigates back reloading the page. Each framework has a different method of going back so we didn't have a way to implement a go back functionality that would work across all frameworks.
